### ISSUE TITLE
Error while building native image

### ISSUE THREAD

**Issue by anthonydenecheau** [maxday/quarkus-native-build-docker-action#8]
I get an error 

`Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project wisdom: Fatal error compiling: invalid target release: 11 -> [Help 1]`

Try to add step 
```
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'        
      - name: Build native executable
```

But issue is still here ...

Help will be appreciate
